clone_depth: 10

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off

cache:
  - node_modules -> appveyor.yml,package.json,package-lock.json
